version: '3'

services:
  mongodb:
    container_name: mongo-libros
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
        MONGO_INITDB_DATABASE: librosdb