version: '3'

services:
  mongodb:
    container_name: mongo-libros
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
        MONGO_INITDB_DATABASE: librosdb
    networks:
      - boston
  
  book-category:
    container_name: book-category
    build: ../cloudinary/
    ports: 
      - '3000:3000'
    depends_on:
      - 'mongodb'
    environment:
      MONGO_INITDB_DATABASE: librosdb
    networks:
      - boston

networks:
  boston:
    driver: bridge